source 'https://rubygems.org'

gem 'base64'
gem 'bigdecimal'
gem 'builder'
gem 'csv'
gem 'fiddle'
gem 'logger'
gem 'middleman', '~> 4.5'
gem 'middleman-autoprefixer', '~> 3.0'
gem 'middleman-livereload'
gem 'middleman-syntax'
gem 'mutex_m'
gem 'ostruct'
gem 'rdoc'
gem 'sass-embedded'
gem 'terser', '~> 1.1'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby, :x64_mingw]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw, :x64_mingw]
